#!/usr/bin/env python
import rdioexport
import signal
import sys


def sigint_handler(signal, frame):
    print "\nQuitting..."
    sys.exit(0)
signal.signal(signal.SIGINT, sigint_handler)

if __name__ == '__main__':
    rdio = rdioexport.get_rdio_client()

    collection = rdio.get_collection_by_album()

    num_albums = 0
    num_tracks = 0
    for album in collection:
        num_albums += 1
        num_tracks += len(album['trackKeys'])

    print u"Collection size: {} albums with {} tracks".format(
        num_albums,
        num_tracks,
    )
