#!/usr/bin/env python
import rdioexport
import signal
import os
import sys
from tempfile import mkdtemp


def sigint_handler(signal, frame):
    print u"\nQuitting..."
    sys.exit(0)
signal.signal(signal.SIGINT, sigint_handler)


if __name__ == '__main__':
    rdio = rdioexport.get_rdio_client()

    temp_dirname = mkdtemp()
    print u"Writing to {}".format(temp_dirname)

    album_filename = os.path.join(temp_dirname, 'albums.ndjson')
    track_filename = os.path.join(temp_dirname, 'tracks.ndjson')
    playlist_filename = os.path.join(temp_dirname, 'playlists.ndjson')

    exporter = rdioexport.get_exporter(
        album_filename,
        track_filename,
        playlist_filename)
    rdioexport.archive_collection(rdio, exporter)
    rdioexport.archive_playlists(rdio, exporter)

    print u"\nExport data written to {}".format(temp_dirname)
